# Global options:

[mypy]
ignore_missing_imports=True
strict_optional=False
non_interactive=True
install_types=True
plugins = pydantic.mypy

#mypy_path = "./stubs"

# Per-module options:
#[mypy-mycode.foo.*]
#disallow_untyped_defs = True
