[tool.poetry]
name = "flask-tactful"
version = "0.2.13"
description = "Flask Utilities used by Tactful AI services"
authors = ["Tactful AI <dev@tactful.ai>"]

[tool.poetry.dependencies]
python = "~3.8"
Flask = "2.1.2"
Werkzeug = "2.0.3"   
alembic = "^1.8.0"
Flask-Admin = "^1.6.0"
bugsnag = "^4.2.1"
SQLAlchemy = "^1.4.39"
Flask-JWT-Extended = "^4.4.2"
flask-swagger-ui = "^4.11.1"
Flask-SQLAlchemy = "^2.5.1"
Flask-Migrate = "^3.1.0"
flask-restx = "^0.5.1"
flask-kafka = "^0.0.3"
Flask-Login = "^0.6.1"
celery = "^5.2.7"
python-simplexml = "^0.1.5"
pydantic = "^1.9.1"
redis = "^4.5.1"
Sphinx = "^6.1.3"
cryptography = "37.0.4"



[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
notebook = "^6.5.2"
mypy = "^0.961"
pylint = "^2.14.4"
poethepoet = "^0.15.0"
pytest = "^7.1.2"
sphinx-rtd-theme = "^1.2.0"
zundler = {git = "https://github.com/AdrianVollmer/Zundler", rev = "main"}
autopep8 = "^2.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
test = "pytest ."
compile = { shell = "mypy flask_tactful" }
lint = "pylint -f parseable -r n flask_tactful"
login = { shell = "export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token  --region eu-west-1 --domain tactful --domain-owner 409160330780 --query authorizationToken --output text` && poetry config repositories.aws https://tactful-409160330780.d.codeartifact.eu-west-1.amazonaws.com/pypi/ucx-pip/ && poetry config http-basic.aws aws $CODEARTIFACT_AUTH_TOKEN" }
publish = { shell = "export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token  --region eu-west-1 --domain tactful --domain-owner 409160330780 --query authorizationToken --output text` && poetry config repositories.aws https://tactful-409160330780.d.codeartifact.eu-west-1.amazonaws.com/pypi/ucx-pip/ && poetry config http-basic.aws-publish aws $CODEARTIFACT_AUTH_TOKEN  && poetry publish -r aws-publish --skip-existing --build --username aws --password ${CODEARTIFACT_AUTH_TOKEN}" }
#doc = "pdoc flask_tactful  --no-show-source --docformat google"
doc= { shell = "make zundler" }
version = { shell = "poetry version patch && export TAG_VERSION=$(poetry version --short) && git commit -a -m $TAG_VERSION && git tag -a $TAG_VERSION -m $TAG_VERSION  &&  git push && git push --tags" }


[[tool.poetry.source]]
name = "aws"
url = "https://tactful-409160330780.d.codeartifact.eu-west-1.amazonaws.com/pypi/ucx-pip/simple/"
secondary = true


[[tool.poetry.source]]
name = "aws-publish"
url = "https://tactful-409160330780.d.codeartifact.eu-west-1.amazonaws.com/pypi/ucx-pip/"
secondary = true

[tool.pytest.ini_options]
log_level = "WARN"

[tool.autopep8]
max_line_length = 120
ignore = "E501,W6,E11"
in-place = true
recursive = true
aggressive = false
