from typing import Dict, List, Literal,Any, TypedDict , Optional
from flask import Flask, request, jsonify


EventFields = Dict[str, Any] 

class EventDocumentation(TypedDict):
    """Represents documentation for a single event."""
    eventName: str
    service: str
    action: Literal['consume', 'publish']
    topic: Optional[str]
    broker: Optional[Literal['Redis Stream', 'Redis']]
    payloadDescription: EventFields
    description: Optional[str]
    isAutoGenerated: Optional[bool]

class EventDocumentor:
    """
    A utility class to document events consumed and published by the service.

    Provides functionality to:
        - Record event documentation manually
        - Auto-generate documentation for events
        - Update payload documentation dynamically
        - Expose documentation through a web server endpoint
    """
    _events: Dict[str, EventDocumentation] = {}
    _web_server: Flask | None = None

    @staticmethod
    def initialize(app: Flask, api_name: str, api_version: str):
        """
        Initializes the EventDocumentor with a Flask app to expose the documentation endpoint.

        Args:
            app (Flask): The Flask application instance.
        """
        EventDocumentor._web_server = app
        api_prefix = f'/{api_name}/{api_version}'
        app.add_url_rule(f'{api_prefix}/events', 'get_events', EventDocumentor.get_events, methods=['GET'])

    @staticmethod
    def get_events() -> List[EventDocumentation]:
        """
        Returns a list of all documented events.

        Returns:
            List[EventDocumentation]: A list of event documentation dictionaries.
        """
        return list(EventDocumentor._events.values())

    @staticmethod
    def record_event(event: EventDocumentation):
        """
        Registers an event to the list of events this service consumes/publishes.

        Any documentation recorded will not be overwritten by automatic documentation
        generated for events in bus.

        Args:
            event (EventDocumentation): Describes the event & how the service interacts with it.
        """
        if event.get('payloadDescription') is None:
            event['payloadDescription'] = {}
        EventDocumentor._events[event['eventName']] = event

    @staticmethod
    def auto_record_event(event: EventDocumentation):
        """
        Used internally by bus to generate automatic documentation for events.

        Only stores an event if it was never encountered before.

        Does not overwrite events documented using `record_event()`.

        Args:
            event (EventDocumentation): The event documentation to record.
        """
        event_name = event['eventName']
        if EventDocumentor.is_event_defined_manually(event_name) or EventDocumentor.event_has_payload_documentation(event_name):
            return

        event['payloadDescription'] = {}
        EventDocumentor._events[event_name] = event

    @staticmethod
    def update_payload_docs(event_name: str, payload: Any):
        """
        Used internally by bus to generate automatic documentation for event payloads.

        At time of publish/ack, generates a description of the payload object.

        Generated payload description is added to event's docs only if :

        - Event was seen before
        - It was automatically generated (not using `recordEvent()`)
        - No payload description exists for this event.

        EX: ` {a: 1, b: '2'} ` => ` {a: 'number', b: 'string'} `

        Args:
            event_name (str): The name of the event.
            payload (Any): The payload of the event.
        """
        try:
            if not EventDocumentor._events.get(event_name) or \
               EventDocumentor.is_event_defined_manually(event_name) or \
               EventDocumentor.event_has_payload_documentation(event_name):
                return

            payload_docs = EventDocumentor.object_to_description(payload) if payload else {}
            EventDocumentor._events[event_name]['payloadDescription'] = payload_docs
        except Exception as e:
            print(f'Error occurred while updating event documentation: {e}')

    @staticmethod
    def is_event_defined_manually(event_name: str) -> bool:
        """
        Checks if an event was defined manually using `record_event()`.

        Args:
            event_name (str): The name of the event to check.

        Returns:
            bool: True if the event was defined manually, False otherwise.
        """
        event = EventDocumentor._events.get(event_name)
        if not event:
            return False
        return not event.get('isAutoGenerated', True)

    @staticmethod
    def event_has_payload_documentation(event_name: str) -> bool:
        """
        Checks if an event has payload documentation.

        Args:
            event_name (str): The name of the event to check.

        Returns:
            bool: True if the event has payload documentation, False otherwise.
        """
        event = EventDocumentor._events.get(event_name)
        if not event:
            return False
        return bool(event.get('payloadDescription'))

    @staticmethod
    def object_to_description(payload: Any) -> EventFields:
        """
        Transforms any object to it's key: type of value representation

        EX: ``` {a: 1, b: '2', c: { d: [] } } ` => ` {a: 'number', b: 'string', c: { d: 'array'}} `

        Args:
            payload (Any): The object to transform.

        Returns:
            EventFields: The transformed object with key: type representation.
        """
        result: EventFields = {}
        for key, value in payload.items():
            if isinstance(value, dict):
                result[key] = EventDocumentor.object_to_description(value)
            else:
                result[key] = type(value).__name__
        return result
