from dataclasses import dataclass
from typing import Literal, Optional
from datetime import datetime

""" Supported Audiences of Tactful JWT tokens
"""
JWTAudiences = Literal['webchat', 'vdash', 'email']


@dataclass
class JWTPayload:
    """ payload data stored in JWT token """
    email: str
    role: str
    aud: JWTAudiences
    id: Optional[int] = None
    sub: Optional[str] = None
    expires_on: Optional[datetime] = None

    def from_dict(self, payload):
        for field in self.__dataclass_fields__:
            setattr(self, field, payload.get(field))


@dataclass
class JWTAccessPayload(JWTPayload):
    """ Access Token Payload data, it includes the user's profile id (workspace) and their role in that profile
    """
    profile_id: Optional[int] = None
    profile_role: Optional[str] = None


@dataclass
class JWTWebChatPayload(JWTPayload):
    """ Customer facing JWT token, this token is generated by the channels (like webchat or facebook)
      to allow the customer to call the backend services 
    """
    """ channel generated GUID, valid for webchat, on facebook and whatsapp can be facebook ID or whatsapp numbner"""
    guid: Optional[str] = None
    """ Customer database ID """
    customer_id: Optional[int] = None
    """ Channel ID that the customer is visiting from """
    channel_id: Optional[int] = None


@dataclass
class JWTCredintial:
    user_access_token: Optional[str] = None
    user_refresh_token: Optional[str] = None
